"""Research Intelligence Engine.

Transforms extracted knowledge into structured intelligence via
a normalized ResearchGraph and composable analyzers.
"""

from app.modules.intelligence.aggregation import (
    CollaborationSection,
    DatasetSection,
    DiversityMetrics,
    InstitutionEntry,
    InstitutionSection,
    LandscapeAggregator,
    LandscapeResult,
    MethodologyEntry,
    MethodologySection,
    NetworkSection,
    Observation,
    OverviewSection,
    StatisticsSection,
    TechnologySection,
    TemporalSection,
)
from app.modules.intelligence.analyzers import (
    AnalysisResults,
    AnalyzerResult,
    BaseAnalyzer,
    CollaborationAnalyzer,
    DatasetAnalyzer,
    InstitutionAnalyzer,
    IntelligenceEngine,
    MethodologyAnalyzer,
    TechnologyAnalyzer,
    TemporalAnalyzer,
)
from app.modules.intelligence.api import IntelligenceService, LandscapeResponse
from app.modules.intelligence.config import IntelligenceConfig
from app.modules.intelligence.context import AnalysisContext
from app.modules.intelligence.graph import (
    AuthorNode,
    DatasetNode,
    EntityResolver,
    GraphServices,
    InstitutionNode,
    InstitutionType,
    MethodologyNode,
    MetricNode,
    PaperMetadata,
    PaperNode,
    ResearchGraph,
    ResearchGraphBuilder,
    TechnologyNode,
    TechnologyType,
)
from app.modules.intelligence.presentation import (
    BaseRenderer,
    JsonRenderer,
    MarkdownRenderer,
)
from app.modules.intelligence.services import (
    CentralityService,
    CoOccurrenceService,
    SimilarityService,
    StatisticsService,
    TrendService,
)

__all__ = [
    "AnalysisContext",
    "AnalysisResults",
    "AnalyzerResult",
    "AuthorNode",
    "BaseAnalyzer",
    "BaseRenderer",
    "JsonRenderer",
    "MarkdownRenderer",
    "CollaborationSection",
    "DatasetSection",
    "DiversityMetrics",
    "CentralityService",
    "CollaborationAnalyzer",
    "CoOccurrenceService",
    "DatasetAnalyzer",
    "DatasetNode",
    "EntityResolver",
    "GraphServices",
    "InstitutionAnalyzer",
    "InstitutionEntry",
    "InstitutionNode",
    "InstitutionSection",
    "InstitutionType",
    "IntelligenceConfig",
    "IntelligenceEngine",
    "IntelligenceService",
    "LandscapeResponse",
    "LandscapeAggregator",
    "LandscapeResult",
    "MethodologyAnalyzer",
    "MethodologyEntry",
    "MethodologyNode",
    "MethodologySection",
    "MetricNode",
    "NetworkSection",
    "Observation",
    "OverviewSection",
    "PaperMetadata",
    "PaperNode",
    "ResearchGraph",
    "ResearchGraphBuilder",
    "SimilarityService",
    "StatisticsSection",
    "StatisticsService",
    "TechnologyAnalyzer",
    "TechnologySection",
    "TemporalSection",
    "TechnologyNode",
    "TechnologyType",
    "TemporalAnalyzer",
    "TrendService",
]
