"""initial schema

Revision ID: d4bc8ca984b8
Revises: 
Create Date: 2026-06-28 13:08:02.409601
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd4bc8ca984b8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investigations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('topic', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'PLANNING', 'RETRIEVING', 'VALIDATING', 'EXTRACTING', 'ANALYZING', 'GENERATING', 'COMPLETED', 'FAILED', 'CANCELLED', name='investigation_status', create_constraint=True), nullable=False),
    sa.Column('paper_limit', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_investigations'))
    )
    op.create_table('papers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('doi', sa.String(length=255), nullable=True),
    sa.Column('venue', sa.String(length=255), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('citation_count', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_papers')),
    sa.UniqueConstraint('doi', name=op.f('uq_papers_doi'))
    )
    op.create_table('executions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('investigation_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'FAILED', 'COMPLETED', 'CANCELLED', name='execution_status', create_constraint=True), nullable=False),
    sa.Column('trigger', sa.String(length=50), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_executions_investigation_id_investigations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_executions'))
    )
    op.create_index(op.f('ix_executions_investigation_id'), 'executions', ['investigation_id'], unique=False)
    op.create_table('investigation_papers',
    sa.Column('investigation_id', sa.UUID(), nullable=False),
    sa.Column('paper_id', sa.UUID(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_investigation_papers_investigation_id_investigations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], name=op.f('fk_investigation_papers_paper_id_papers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('investigation_id', 'paper_id', name=op.f('pk_investigation_papers'))
    )
    op.create_table('paper_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('paper_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_identifier', sa.String(length=500), nullable=False),
    sa.Column('raw_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], name=op.f('fk_paper_sources_paper_id_papers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_paper_sources'))
    )
    op.create_index(op.f('ix_paper_sources_paper_id'), 'paper_sources', ['paper_id'], unique=False)
    op.create_table('artifacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('investigation_id', sa.UUID(), nullable=False),
    sa.Column('execution_id', sa.UUID(), nullable=True),
    sa.Column('artifact_type', sa.Enum('EXECUTION_PLAN', 'PAPER_COLLECTION', 'VALIDATED_COLLECTION', 'KNOWLEDGE_PACKAGE', 'COMPARISON_MATRIX', 'TREND_REPORT', 'OPPORTUNITY_REPORT', 'RESEARCH_IDEAS', 'FINAL_REPORT', name='artifact_type'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'GENERATING', 'READY', 'FAILED', name='artifact_status'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], name=op.f('fk_artifacts_execution_id_executions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_artifacts_investigation_id_investigations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_artifacts'))
    )
    op.create_index(op.f('ix_artifacts_execution_id'), 'artifacts', ['execution_id'], unique=False)
    op.create_index(op.f('ix_artifacts_investigation_id'), 'artifacts', ['investigation_id'], unique=False)
    op.create_table('investigation_timeline',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('investigation_id', sa.UUID(), nullable=False),
    sa.Column('execution_id', sa.UUID(), nullable=True),
    sa.Column('stage', sa.Enum('CREATED', 'PLANNING', 'RETRIEVING', 'VALIDATING', 'EXTRACTING', 'ANALYZING', 'GENERATING', 'COMPLETED', 'FAILED', 'CANCELLED', name='timeline_stage'), nullable=False),
    sa.Column('status', sa.Enum('SUCCESS', 'FAILURE', 'PENDING', 'RUNNING', name='timeline_status'), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], name=op.f('fk_investigation_timeline_execution_id_executions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_investigation_timeline_investigation_id_investigations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_investigation_timeline'))
    )
    op.create_index(op.f('ix_investigation_timeline_execution_id'), 'investigation_timeline', ['execution_id'], unique=False)
    op.create_index(op.f('ix_investigation_timeline_investigation_id'), 'investigation_timeline', ['investigation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_investigation_timeline_investigation_id'), table_name='investigation_timeline')
    op.drop_index(op.f('ix_investigation_timeline_execution_id'), table_name='investigation_timeline')
    op.drop_table('investigation_timeline')
    op.drop_index(op.f('ix_artifacts_investigation_id'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_execution_id'), table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_index(op.f('ix_paper_sources_paper_id'), table_name='paper_sources')
    op.drop_table('paper_sources')
    op.drop_table('investigation_papers')
    op.drop_index(op.f('ix_executions_investigation_id'), table_name='executions')
    op.drop_table('executions')
    op.drop_table('papers')
    op.drop_table('investigations')
    # ### end Alembic commands ###
